[scripts]
header = """
#!/bin/bash
#$ -S /bin/bash
#$ -cwd
"""
body = """
source ~/.bashrc
source ~/.bash_profile
set -eu
"""

[resource]
default_mem = "4G"
default_slot = "1"
header = """
#$ -l s_vmem={mem} -l mem_req={mem}
#$ -pe def_slot {slot}
"""

[arrayjob]
id = "SEG_TASK_ID"
header = "#$ -t {start}-{end}:{step}"

[options]
sync = ["-sync", "y"]