job_name: "example"

default_mem: 4G
default_slot: 1

test: true
mode: ord
common_variables:
  fasta: "/path/to/fasta"

stages:
  - name: stage1
    cmd: echo $fasta

  - name: stage2
    cmd: echo "hello, world"
    mem: 4G
    slot: 1

  - name: stage3
    cmd: echo $elem
    mem: 4G
    slot: 1
    ls: "*.py"

  - name: stage4
    cmd: echo $elem
    array_cmd: echo 'a b'

    