job_name: "example"

default_mem: 4G
default_slot: 1

common_variable:
  fasta: /path/to/fasta

stages:
  - name: stage1
    cmd: echo $fasta

  - name: stage2
    cmd: echo "hello, world"
    mem: 4G
    slot: 1

  - name: stage3
    cmd: echo $file
    mem: 4G
    slot: 1
    ls: "*.py"

    