job-name: "example"

default-mem: 4G
default-slot: 1

mode: ord
common-variables:
  fasta: "/path/to/fasta"
  seq: "'1 2'"

stages:
  - name: stage1
    cmd: echo $fasta

  - name: stage2
    cmd: echo "hello, world"
    mem: 4G
    slot: 1

  - name: stage3
    cmd: echo $elem
    mem: 4G
    slot: 1
    ls: "*.py"

  - name: stage4
    cmd: echo $elem
    array-cmd: echo 'a b'

  - name: stage5
    run: echo $elem
    array-cmd: echo $seq
    runs-on: "salmon"
    bind-dirs: 
      - /LARGE0/gr10289:/LARGE0/gr10289
      - /LARGE0/gr10289/RNAseq:/mnt

    
